= Prequiz

== Instructions

Pretend we're taking a closed-book exam and *modify this file* to answer the questions below.
Don't worry, this is not being graded for correctness: guesses or even admissions of ignorance are okay.
The point is to asses your knowledge beforehand as a frame of reference.

When you are done:

----
cd ~/COMP603-2015
# The easy way
git gui &
# The leet way
git add .
git commit -m "Finished prequiz"
git push -u --all origin
----

== Questions

What is the difference between a set, a bag, and a sequence? Don't know


What is a language (in terms of sets and sequences)?  A form of communication, in programming a way to communicate with the computer.


What is a compiler? Name some. Makes code into language the computer can understand. javac, C++


What is an interpreter? How does that differ from a compiler? Don't remember


What is the derivative of a language? Don't know


What is a regular expression? A wildcard


What is a finite automaton, and what is the difference between an NFA and a DFA? Don't know


What is a grammar, and what is the difference between regular grammars, context-free grammars, LL(k) and LR(k)? Don't know


What is the difference between derivative parsing, recursive-descent parsing, shift-reduce parsing and parser combinators? Don't know


What is a visitor? An extraterrestrial


What is the difference between a parse tree and an abstract syntax tree? Parse tree contains all information of an input.


Name some optimizations. 


What questions do you have for me?

